### PR TITLE
Some property name changes

### PR DESCRIPTION
**Pull request by flatsiedatsie**
These names would make the addon easier to use with voice control.

### CODE REVIEW

**Comment by tim-hellhake** [comment]
As mentioned before, I don't think it makes sense to change every single adapter just to fix one.
The title is meant to be read by humans, not machines.
Imposing implicit restrictions on it leads to a tight coupling between the adapters, which is generally a bad idea.

**Comment by tim-hellhake** [comment]
I agree though that the `CPU` in `CPU temperature` might be superfluous.
I'm currently checking what additional CPU info could be exposed so the title might change soon anyway.

**Comment by flatsiedatsie** [comment]
Well, most of the proposed names are easier to understand for normal people too? My mom may know what a processor is, but not what a CPU is. Similarly, "IO" is less descriptive to normal people than "Disk activity". 

Similarly, having multiple properties with identical names in one device makes it hard to select those properties in rules/logs/etc.

So it's not just about Voice control. And for the record: having pronouncable names would help any voice control addon, not just Voco.

**Comment by tim-hellhake** [comment]
> Similarly, "IO" is less descriptive to normal people than "Disk activity".

I'm confused, where did you see `IO`?

> Similarly, having multiple properties with identical names in one device makes it hard to select those properties in rules/logs/etc.

I totally agree, but are there any identical titles left?

**Comment by flatsiedatsie** [comment]
> I totally agree, but are there any identical titles left?

I only saw your other change after readin this one, sorry. Very nice.

> I'm confused, where did you see IO?

io

Top right?

**Comment by tim-hellhake** [comment]
> Top right?

That's LO not IO.
`lo` is the loopback device.
It's a virtual network card for `127.0.0.1`.

**Comment by flatsiedatsie** [comment]
Ah, ok. Well, there you go :-)

What does that do? I take it it's not the same speed measurement as the wifi transmission. Does it measure how much the UI talks to the backend? And what do the properties represent?

**Comment by tim-hellhake** [comment]
> What does that do? I take it it's not the same speed measurement as the wifi transmission.

It's like `wlan0` just for local traffic that won't leave the system.
All traffic that goes to `127.0.0.1` or `localhost` will be tracked by this device.
For example, the communication between an adapter and the gateway will influence the speed measurement.

> Does it measure how much the UI talks to the backend?

The UI usually runs in a browser on another system.
Therefore it would be `wlan0` in your case.
If you access the gateway on the same system via `localhost` it will be `lo` though.

> And what do the properties represent?

The properties are the same as for any other network card.

**Pull request closed without merging**
